import os
DATA = "/data/"
CONFIGS = "configs/"
DATA_SRC = "data_src/"
DATA_DEST = "data_dest/"
CWD = os.getcwd()

SUBPARSER_CLUS = "clus"
SUBPARSER_CONF = "conf"
SUBPARSER_PREP = "prep"

HDBSCAN = "hdbscan"
HIERARCHICAL = "hierarchical"
QT = "qt"
QTVECTOR = "qtvector"
IMWKMEANS = "imwkmeans"
TSNE = "tsne"
UMAP = "umap"

CONFIGURATION = "--configuration"
ALGORITHM = "--algorithm"
SOURCE = "--source"
DESTINATION = "--destination"
VISUALISE = "--visualise"
VALIDATE = "--validate"
DOWNSAMPLE = "--downsample"
FRAMESELECT = "--frameselect"
SELECTION = "--selection"
SAVECLUSTERS = "--saveclusters"
LINKAGE = "--linkage"
MINCLUSTERSIZE = "--minclustersize"
MINSAMPLES = "--minsamples"
QUALITYTHRESHOLD = "--qualitythreshold"
K_CLUSTERS = "--numberofclusters"
DDISTANCE = "--dendrogramdistance"
PREPROCESS = "--preprocess"

N_COMPONENTS = "--ncomponents"
N_NEIGHBOURS = "--nneighbours"

AVERAGE = "average"
COMPLETE = "complete"
SINGLE = "single"
WARD = "ward"

SILHOUETTE = "S"
DAVIESBOULDIN = "DB"
CALINSKIHARABASZ = "CH"

IRIS = "iris"
DIGITS = "digits"
WINE = "wine"
BREASTCANCER = "breastcancer"
NOISE = "noise"
BLOBS = "blobs"
VBLOBS = "vblobs"
TEST = "--test"
