SUBPARSER_CLUS = "clus"
SUBPARSER_CONF = "conf"
SUBPARSER_PREP = "prep"

HDBSCAN = "hdbscan"
HIERARCHICAL = "hierarchical"
QT = "qt"
QTVECTOR = "qtvector"
IMWKMEANS = "imwkmeans"
TSNE = "tsne"
UMAP = "umap"


CONFIGURATION = "--configuration"
ALGORITHM = "--algorithm"
SOURCE = "--source"
DESTINATION = "--destination"
VISUALISE = "--visualise"
VALIDATE = "--validate"
DOWNSAMPLE = "--downsample"
SELECTION = "--selection"
SAVECLUSTERS = "--saveclusters"
LINKAGE = "--linkage"
MINCLUSTERSIZE = "--minclustersize"
MINSAMPLES = "--minsamples"

AVERAGE = "average"
COMPLETE = "complete"
SINGLE = "single"
WARD = "ward"

SILHOUETTE = "S"
DAVIESBOULDIN = "DB"
CALINSKIHARABASZ = "CH"
